service: websoket-lambda

custom:
  dev:
  uat:
  prod:

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-2
  endpointType: regional
  versionFunctions: false
  memorySize: 128
  timeout: 6
  logs:
    websocket:
      level: ERROR
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [DataTable, Arn]
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - Ref: LoopBackTopic

package:
  individually: true
  exclude:
    - ./**

functions:
  api:
    handler: bin/connectionmanager
    package:
      include:
        - ./bin/connectionmanager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
    environment:
      TOPIC_ARN: 
        Ref: LoopBackTopic
  messages:
    handler: bin/messages
    package:
      include:
        - ./bin/messages
    events:
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default
  pushfromsns:
    handler: bin/loopback
    package:
      include:
        - ./bin/loopback
    events:
      - sns: 
          arn: !Ref LoopBackTopic
          topicName: ${self:service}-${opt:stage, self:provider.stage}-loopback

resources:
  Resources:
    DataTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}-data
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        Tags:
          - Key: Environment
            Value: ${opt:stage, self:provider.stage}
        TimeToLiveSpecification:
            AttributeName: ttl
            Enabled: TRUE
    
    LoopBackTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:service}-${opt:stage, self:provider.stage}-loopback
        Tags:
          - Key: Environment
            Value: ${opt:stage, self:provider.stage}
